# Generated by Django 4.1.2 on 2022-10-19 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Osoba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=60)),
                ('nazwisko', models.CharField(max_length=60)),
                ('miasiac_urodzenia', models.CharField(choices=[('1', 'Styczen'), ('2', 'Luty'), ('3', 'Marzec'), ('4', 'Kwiecien'), ('5', 'Maj'), ('6', 'Czerwiec'), ('7', 'Lipiec'), ('8', 'Sierpien'), ('9', 'Wrzesien'), ('10', 'Pazdziernik'), ('11', 'Listopad'), ('12', 'Grudzien')], max_length=2)),
            ],
        ),
    ]
