# Generated by Django 4.1.2 on 2022-10-19 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_druzyna_alter_osoba_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='druzyna',
            name='kraj',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='polls.osoba'),
        ),
    ]
