# Generated by Django 4.1.2 on 2022-10-19 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_alter_druzyna_kraj'),
    ]

    operations = [
        migrations.AddField(
            model_name='osoba',
            name='kraj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.druzyna'),
        ),
        migrations.AlterField(
            model_name='druzyna',
            name='kraj',
            field=models.CharField(max_length=2),
        ),
    ]
