# Generated by Django 4.1.2 on 2022-11-09 11:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_osoba_kraj_alter_druzyna_kraj'),
    ]

    operations = [
        migrations.AddField(
            model_name='osoba',
            name='miesiac_dodania',
            field=models.CharField(choices=[('1', 'styczeń'), ('2', 'luty'), ('3', 'marzec'), ('4', 'kwiecień'), ('5', 'maj'), ('6', 'czerwiec'), ('7', 'lipiec'), ('8', 'sierpień'), ('9', 'wrzesień'), ('10', 'październik'), ('11', 'listopad'), ('12', 'grudzień')], default=11, max_length=255),
        ),
        migrations.AlterField(
            model_name='druzyna',
            name='kraj',
            field=models.CharField(max_length=2, validators=[django.core.validators.RegexValidator('^[A-Z]', 'Tylko duże litery')]),
        ),
        migrations.AlterField(
            model_name='druzyna',
            name='nazwa',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='osoba',
            name='imie',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+$', 'Tylko litery')]),
        ),
        migrations.AlterField(
            model_name='osoba',
            name='kraj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.druzyna'),
        ),
        migrations.AlterField(
            model_name='osoba',
            name='miesiac_urodzenia',
            field=models.CharField(choices=[('1', 'styczeń'), ('2', 'luty'), ('3', 'marzec'), ('4', 'kwiecień'), ('5', 'maj'), ('6', 'czerwiec'), ('7', 'lipiec'), ('8', 'sierpień'), ('9', 'wrzesień'), ('10', 'październik'), ('11', 'listopad'), ('12', 'grudzień')], default=11, max_length=255),
        ),
        migrations.AlterField(
            model_name='osoba',
            name='nazwisko',
            field=models.CharField(max_length=255),
        ),
    ]
